import * as B from '@babylonjs/core';
import nebulaUrl from '../assets/nebula.webp';

type UI={score:Element;shield:Element;wave:Element;combo:Element;comboValue:Element};
type Projectile={mesh:B.Mesh;velocity:B.Vector3;life:number};
type Drone={mesh:B.Mesh;hp:number;cool:number;phase:number};
type Crystal={mesh:B.Mesh;spin:number;value:number};

const C={cyan:'#55efff',pink:'#ff4fce',purple:'#9b5cff',gold:'#ffe36e',dark:'#090c24'};
function mat(scene:B.Scene,name:string,color:string,glow=0){const m=new B.StandardMaterial(name,scene);m.diffuseColor=B.Color3.FromHexString(color);m.emissiveColor=B.Color3.FromHexString(color).scale(glow||.15);m.specularColor=new B.Color3(.2,.2,.35);return m}
function glow(scene:B.Scene,meshes:B.Mesh[]){const l=new B.GlowLayer('neon-glow',scene);l.intensity=1.25;meshes.forEach(x=>l.addIncludedOnlyMesh(x));return l}
function makeShip(scene:B.Scene):B.Mesh{const root=B.MeshBuilder.CreateBox('ship-root',{size:1},scene);root.isVisible=false;const body=B.MeshBuilder.CreateCylinder('ship-body',{height:2.2,diameterTop:.18,diameterBottom:1.15,tessellation:5},scene);body.rotation.x=Math.PI/2;body.parent=root;body.material=mat(scene,'ship-cyan',C.cyan,.8);const wingL=B.MeshBuilder.CreateBox('wing-l',{width:1.8,height:.1,depth:.55},scene);wingL.position.x=-.95;wingL.position.z=.18;wingL.parent=root;wingL.rotation.z=-.12;wingL.material=mat(scene,'wing-pink',C.pink,.7);const wingR=wingL.clone('wing-r')!;wingR.position.x=.95;wingR.rotation.z=.12;wingR.parent=root;const cockpit=B.MeshBuilder.CreateSphere('cockpit',{diameter:.48,segments:12},scene);cockpit.position.y=.28;cockpit.position.z=-.1;cockpit.parent=root;cockpit.material=mat(scene,'cockpit',C.purple,1);const thrusterL=B.MeshBuilder.CreateCylinder('thruster-l',{height:.28,diameter:.2},scene);thrusterL.position.set(-.35,0,.92);thrusterL.rotation.x=Math.PI/2;thrusterL.parent=root;thrusterL.material=mat(scene,'thruster',C.gold,1);const thrusterR=thrusterL.clone('thruster-r')!;thrusterR.position.x=.35;thrusterR.parent=root;glow(scene,[body,wingL,wingR,cockpit,thrusterL,thrusterR]);return root}
function makeDrone(scene:B.Scene):B.Mesh{const root=B.MeshBuilder.CreateSphere('drone',{diameter:1.2,segments:8},scene);root.scaling.y=.65;root.material=mat(scene,'drone-core',C.pink,.8);const ring=B.MeshBuilder.CreateTorus('drone-ring',{diameter:1.8,thickness:.1,tessellation:8},scene);ring.parent=root;ring.rotation.x=Math.PI/2;ring.material=mat(scene,'drone-ring',C.purple,.9);const eye=B.MeshBuilder.CreateSphere('drone-eye',{diameter:.25},scene);eye.position.z=-.58;eye.parent=root;eye.material=mat(scene,'drone-eye',C.gold,1);glow(scene,[root,ring,eye]);return root}
function makeAsteroid(scene:B.Scene,pos:B.Vector3,size:number):B.Mesh{const a=B.MeshBuilder.CreateIcoSphere('asteroid',{radius:size,subdivisions:1},scene);a.position.copyFrom(pos);a.scaling.set(1.1,.8,.9);a.rotation.set(Math.random(),Math.random(),Math.random());a.material=mat(scene,'asteroid', '#242649',.08);const ring=B.MeshBuilder.CreateTorus('asteroid-rim',{diameter:size*1.8,thickness:.035,tessellation:7},scene);ring.parent=a;ring.material=mat(scene,'asteroid-rim',C.purple,.22);return a}
function makeCrystal(scene:B.Scene):B.Mesh{const c=B.MeshBuilder.CreatePolyhedron('crystal',{type:1,size:1.05},scene);c.scaling.y=1.5;c.material=mat(scene,'crystal',C.purple,1);glow(scene,[c]);return c}
function pulse(mesh:B.Mesh,t:number){mesh.scaling.setAll(1+Math.sin(t*5)*.06)}

 export function createGameScene(engine:B.Engine,canvas:HTMLCanvasElement,ui:UI){const scene=new B.Scene(engine);scene.clearColor=new B.Color4(.015,.018,.07,1);scene.fogMode=B.Scene.FOGMODE_EXP2;scene.fogDensity=.008;scene.fogColor=new B.Color3(.02,.02,.1);
 const camera=new B.UniversalCamera('camera',new B.Vector3(0,16,-28),scene);camera.setTarget(new B.Vector3(0,0,4));camera.fov=.92;scene.activeCamera=camera;
 const backdrop=B.MeshBuilder.CreatePlane('nebula-backdrop',{size:2},scene);backdrop.scaling.set(58,34,1);backdrop.position.set(0,16,43);const backdropMat=new B.StandardMaterial('nebula-material',scene);backdropMat.diffuseTexture=new B.Texture(nebulaUrl,scene);backdropMat.emissiveTexture=backdropMat.diffuseTexture;backdropMat.emissiveColor=new B.Color3(.35,.25,.65);backdropMat.disableLighting=true;backdrop.material=backdropMat;
 const hemi=new B.HemisphericLight('space-fill',new B.Vector3(0,1,0),scene);hemi.intensity=.5;hemi.diffuse=B.Color3.FromHexString('#8c83ff');const key=new B.PointLight('cyan-key',new B.Vector3(0,7,-10),scene);key.diffuse=B.Color3.FromHexString(C.cyan);key.intensity=80;key.range=30;const mag=new B.PointLight('magenta-key',new B.Vector3(12,4,12),scene);mag.diffuse=B.Color3.FromHexString(C.pink);mag.intensity=90;mag.range=32;
 const arena=B.MeshBuilder.CreateDisc('arena',{radius:31,tessellation:64},scene);arena.rotation.x=Math.PI/2;arena.material=mat(scene,'arena-floor','#11163b',.2);const grid=B.MeshBuilder.CreateTiledGround('grid',{xmin:-30,zmin:-24,xmax:30,zmax:24,subdivisions:{w:12,h:12}},scene);const gridMat=mat(scene,'grid-lines','#1a2450',.4);grid.material=gridMat;grid.position.y=.02;
 const stars:B.Mesh[]=[];for(let i=0;i<120;i++){const s=B.MeshBuilder.CreateSphere('star',{diameter:Math.random()*.12+.03},scene);s.position.set((Math.random()-.5)*80,Math.random()*35+5,(Math.random()-.5)*80);s.material=mat(scene,'star','#b3c8ff',Math.random()*.9+.2);stars.push(s)}glow(scene,stars);
 const asteroids=B.MeshBuilder.CreateBox('arena-ring',{width:60,height:.3,depth:48},scene);asteroids.position.y=-.25;asteroids.material=mat(scene,'boundary','#2a1f5e',.4);const debris=[[-19,0,5,2.4],[16,0,8,2.1],[-11,0,15,1.6],[21,0,-8,1.3],[-22,0,-10,1.9],[7,0,20,1.5]].map(p=>makeAsteroid(scene,new B.Vector3(p[0],p[1],p[2]),p[3]));
 const player=makeShip(scene);player.position.set(0,.7,-12);const drones:Drone[]=[];const crystals:Crystal[]=[];const bullets:Projectile[]=[];const enemyBullets:Projectile[]=[];const keys=new Set<string>();let running=false,demo=false,score=0,shield=100,wave=1,combo=1,comboTime=0,spawnClock=0,crystalClock=0,shotCooldown=0,total=0;
 const down=(e:KeyboardEvent)=>{keys.add(e.key);if(e.key===' '){e.preventDefault()}};const up=(e:KeyboardEvent)=>keys.delete(e.key);window.addEventListener('keydown',down);window.addEventListener('keyup',up);canvas.addEventListener('pointerdown',()=>keys.add(' '));canvas.addEventListener('pointerup',()=>keys.delete(' '));
 function spawnDrone(){const d=makeDrone(scene);const side=Math.random()>.5?1:-1;d.position.set((Math.random()-.5)*42,1+Math.random()*7,Math.random()*22+2);drones.push({mesh:d,hp:2,cool:1+Math.random(),phase:Math.random()*5});}
 function spawnCrystal(){const c=makeCrystal(scene);c.position.set((Math.random()-.5)*42,1+Math.random()*3,Math.random()*26-2);crystals.push({mesh:c,spin:Math.random()*4,value:100});}
 for(let i=0;i<5;i++)spawnDrone();for(let i=0;i<5;i++)spawnCrystal();
 function shoot(){if(shotCooldown>0)return;shotCooldown=.16;const b=B.MeshBuilder.CreateSphere('bolt',{diameter:.22},scene);b.position=player.position.add(new B.Vector3(0,.1,1.1));b.material=mat(scene,'bolt',C.cyan,1);bullets.push({mesh:b,velocity:new B.Vector3(0,0,28),life:2});}
 function enemyShoot(d:Drone){const b=B.MeshBuilder.CreateSphere('enemy-bolt',{diameter:.18},scene);b.position.copyFrom(d.mesh.position);b.material=mat(scene,'enemy-bolt',C.pink,1);const v=player.position.subtract(b.position).normalize().scale(12);enemyBullets.push({mesh:b,velocity:v,life:3})}
 function hitPlayer(){shield=Math.max(0,shield-12);ui.shield.setAttribute('style',`width:${shield}%`);player.scaling.setAll(1.25);setTimeout(()=>player.scaling.setAll(1),100);if(shield<=0){shield=100;score=Math.max(0,score-500);}}
 function update(dt:number){if(!running)return;total+=dt;spawnClock-=dt;crystalClock-=dt;shotCooldown-=dt;comboTime-=dt;if(comboTime<0){combo=1;ui.combo.classList.remove('on')}if(demo){keys.add(total%4<2?'ArrowLeft':'ArrowRight');if(Math.sin(total*3)>-.4)keys.add(' ')}
  const dx=(keys.has('a')||keys.has('ArrowLeft')?-1:0)+(keys.has('d')||keys.has('ArrowRight')?1:0);const dz=(keys.has('w')||keys.has('ArrowUp')?1:0)+(keys.has('s')||keys.has('ArrowDown')?-1:0);player.position.x=B.Scalar.Clamp(player.position.x+dx*dt*13,-25,25);player.position.z=B.Scalar.Clamp(player.position.z+dz*dt*13,-18,21);player.rotation.z=B.Scalar.Lerp(player.rotation.z,-dx*.2,.1);if(keys.has(' '))shoot();
  if(spawnClock<=0){spawnClock=Math.max(.8,2.6-wave*.12);spawnDrone();if(drones.length>12)drones.shift()!.mesh.dispose();}if(crystalClock<=0){crystalClock=2.2;spawnCrystal();if(crystals.length>12)crystals.shift()!.mesh.dispose();}if(score>wave*2500){wave++;ui.wave.textContent=String(wave).padStart(2,'0')}
  for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.mesh.position.addInPlace(b.velocity.scale(dt));b.life-=dt;let remove=b.life<0;for(let j=drones.length-1;j>=0&&!remove;j--){const d=drones[j];if(B.Vector3.Distance(b.mesh.position,d.mesh.position)<1.25){d.hp--;remove=true;if(d.hp<=0){d.mesh.dispose();drones.splice(j,1);combo=Math.min(9,combo+1);comboTime=2.5;score+=250*combo;ui.combo.classList.add('on');ui.comboValue.textContent=`x${combo}`}}}if(remove){b.mesh.dispose();bullets.splice(i,1)}}
  for(let i=drones.length-1;i>=0;i--){const d=drones[i];d.phase+=dt;d.mesh.position.y+=Math.sin(d.phase*2)*dt*.7;const dir=player.position.subtract(d.mesh.position).normalize();d.mesh.position.addInPlace(dir.scale(dt*(1.5+wave*.12)));d.mesh.rotation.y+=dt*2;if(B.Vector3.Distance(d.mesh.position,player.position)<1.5){hitPlayer();d.mesh.position.z+=4}d.cool-=dt;if(d.cool<0){d.cool=1.4;enemyShoot(d)}}
  for(let i=enemyBullets.length-1;i>=0;i--){const b=enemyBullets[i];b.mesh.position.addInPlace(b.velocity.scale(dt));b.life-=dt;if(B.Vector3.Distance(b.mesh.position,player.position)<1.3){hitPlayer();b.life=-1}if(b.life<0){b.mesh.dispose();enemyBullets.splice(i,1)}}
  for(let i=crystals.length-1;i>=0;i--){const c=crystals[i];c.spin+=dt;c.mesh.rotation.y=c.spin;c.mesh.position.y+=Math.sin(c.spin*2)*dt*.25;pulse(c.mesh,total);if(B.Vector3.Distance(c.mesh.position,player.position)<1.8){score+=c.value*combo;comboTime=2.5;combo=Math.min(9,combo+1);ui.combo.classList.add('on');ui.comboValue.textContent=`x${combo}`;c.mesh.dispose();crystals.splice(i,1)}}
  player.position.y=.8+Math.sin(total*7)*.06;camera.position.x=B.Scalar.Lerp(camera.position.x,player.position.x*.32,.04);camera.setTarget(new B.Vector3(player.position.x*.15,1,4));ui.score.textContent=String(Math.floor(score)).padStart(6,'0');
 }
 scene.onBeforeRenderObservable.add(()=>update(scene.getEngine().getDeltaTime()/1000));
 return {scene,start:(isDemo=false)=>{running=true;demo=isDemo},keys,dispose:()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);canvas.removeEventListener('pointerdown',()=>keys.add(' '));scene.dispose()}};
}
