import { Engine } from '@babylonjs/core/Engines/engine';
import { createGameScene } from './game/scene';
import './style.css';

const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<canvas id="game" aria-label="Neon Void Runner"></canvas><div class="start" id="start"><div class="card"><div class="eyebrow">SECTOR 07 // VOID RIFT</div><div class="title">NEON VOID</div><div class="subtitle">شکارچیان خلأ را نابود کن، کریستال‌های انرژی را جمع کن<br>و رکورد کمبوی خودت را بشکن.</div><button class="startbtn" id="startBtn">ورود به میدان</button><div class="mission">WASD / ARROWS حرکت · SPACE شلیک · MOUSE هدف‌گیری</div></div></div><div class="hud"><div class="topbar"><div><div class="brand">NEON VOID</div><div class="mission">HUNTERS OF THE RIFT</div></div><div class="stats"><div class="panel"><div class="label">امتیاز / SCORE</div><div class="value" id="score">000000</div></div><div class="panel"><div class="label">سپر / SHIELD</div><div class="shield"><i id="shield"></i></div></div><div class="panel"><div class="label">موج / WAVE</div><div class="value" id="wave">01</div></div></div></div><div class="combo" id="combo"><span>COMBO</span><strong id="comboValue">x2</strong></div><div class="crosshair"></div><div class="bottom"><div class="hint"><b>ماموریت:</b> پهپادها را شکار کن و کریستال‌های بنفش را از میدان جمع کن.<br><b>کنترل:</b> حرکت با WASD · شلیک با Space یا کلیک</div><div class="touch"><button data-key="ArrowLeft">◀</button><button data-key="ArrowUp">▲</button><button data-key="ArrowDown">▼</button><button data-key="ArrowRight">▶</button><button class="fire" id="touchFire">✦</button></div></div></div>`;
const canvas=document.querySelector<HTMLCanvasElement>('#game')!;const engine=new Engine(canvas,true,{preserveDrawingBuffer:true,stencil:true,adaptToDeviceRatio:true});
const ui={score:document.querySelector('#score')!,shield:document.querySelector('#shield')!,wave:document.querySelector('#wave')!,combo:document.querySelector('#combo')!,comboValue:document.querySelector('#comboValue')!};
const game=createGameScene(engine,canvas,ui);engine.runRenderLoop(()=>game.scene.render());window.addEventListener('resize',()=>engine.resize());
const start=document.querySelector('#start')!;document.querySelector('#startBtn')!.addEventListener('click',()=>{start.classList.add('hidden');game.start();});
for(const b of document.querySelectorAll<HTMLButtonElement>('[data-key]')){const k=b.dataset.key!;b.addEventListener('pointerdown',()=>game.keys.add(k));b.addEventListener('pointerup',()=>game.keys.delete(k));b.addEventListener('pointerleave',()=>game.keys.delete(k));}document.querySelector('#touchFire')!.addEventListener('pointerdown',()=>game.keys.add(' '));document.querySelector('#touchFire')!.addEventListener('pointerup',()=>game.keys.delete(' '));
if(location.search.includes('demo')){start.classList.add('hidden');game.start(true)}
